on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - run: ls -la

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: python --version

      - name: Install dependencies
        runs: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    needs: build

    steps:
      - run: ls -la

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: python --version

      - name: Install dependencies
        runs: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest